"use client";import {useEffect,useMemo,useState} from "react";import {supabaseBrowser as supabase} from "@/lib/supabase/supabaseBrowser";
type Source="core"|"gis"|"other"|"derived";type Method="ratio"|"multiply"|"sum"|"difference";type DatasetOption={id:string;title:string;source:Source;table:string;defaultCol?:string|null;adminLevel?:string|null};type TaxoMap=Record<string,string[]>;type Props={open:boolean;onClose:()=>void;countryIso:string;editDataset?:any|null};const ACCENT="#640811";
export default function DerivedDatasetWizard({open,onClose,countryIso,editDataset=null}:Props){const[loading,setLoading]=useState(false);const[datasets,setDatasets]=useState<DatasetOption[]>([]);const[datasetA,setDatasetA]=useState<DatasetOption|null>(null);const[datasetB,setDatasetB]=useState<DatasetOption|null>(null);const[colA,setColA]=useState("");const[colB,setColB]=useState("");const[method,setMethod]=useState<Method>("ratio");const[useScalarB,setUseScalarB]=useState(false);const[scalarB,setScalarB]=useState<number>(1);const[normalizePct,setNormalizePct]=useState(false);const[isParametric,setIsParametric]=useState(true);const[title,setTitle]=useState("");const[desc,setDesc]=useState("");const[targetLevel,setTargetLevel]=useState("ADM3");const[decimals,setDecimals]=useState(2);const[preview,setPreview]=useState<any[]>([]);const[loadingPreview,setLoadingPreview]=useState(false);const[taxoMap,setTaxoMap]=useState<TaxoMap>({});const[taxonomy,setTaxonomy]=useState<Record<string,Set<string>>>({});const groupOrder:Source[]=["core","gis","other","derived"];
// load datasets
useEffect(()=>{if(!open)return;setLoading(true);(async()=>{try{const base:DatasetOption[]=[{id:"core-pop",title:"Population Data",source:"core",table:"population_data",defaultCol:"population",adminLevel:"ADM4"},{id:"core-gis",title:"GIS Features",source:"gis",table:"gis_features",defaultCol:"area_sqkm",adminLevel:"ADM3"}];const {data:others,error:oErr}=await supabase.from("dataset_metadata").select("id,title,country_iso,admin_level").eq("country_iso",countryIso);if(!oErr&&others){others.forEach((r:any)=>base.push({id:r.id,title:r.title,source:"other",table:`dataset_${r.id}`,defaultCol:null,adminLevel:r.admin_level??null}))}const {data:ders,error:dErr}=await supabase.from("derived_dataset_metadata").select("id,title,country_iso").eq("country_iso",countryIso);if(!dErr&&ders){ders.forEach((r:any)=>base.push({id:r.id,title:r.title,source:"derived",table:`derived_${r.id}`,defaultCol:"derived",adminLevel:null}))}setDatasets(base)}finally{setLoading(false)}})()},[open,countryIso]);
// load taxonomy (flat categories with terms)
useEffect(()=>{if(!open)return;(async()=>{const {data}=await supabase.from("taxonomy_terms").select("category,name");if(!data){setTaxoMap({});return}const grouped:TaxoMap={};data.forEach((t:any)=>{grouped[t.category]=grouped[t.category]||[];if(!grouped[t.category].includes(t.name))grouped[t.category].push(t.name)});setTaxoMap(grouped)})()},[open]);
// hydrate on edit
useEffect(()=>{if(!open)return;if(!editDataset){setTitle("");setDesc("");setTargetLevel("ADM3");setMethod("ratio");setUseScalarB(false);setScalarB(1);setNormalizePct(false);setIsParametric(true);setColA("");setColB("");setDecimals(2);setDatasetA(null);setDatasetB(null);setPreview([]);setTaxonomy({});return}setTitle(editDataset.title??"");setDesc(editDataset.description??"");setTargetLevel(editDataset.target_level||editDataset.admin_level||"ADM3");setMethod(((editDataset.method||"ratio") as Method));setUseScalarB(!!editDataset.use_scalar_b);setScalarB(editDataset.scalar_b_val??1);setNormalizePct(!!editDataset.normalize_percent);setIsParametric(editDataset.is_parametric??true);setColA(editDataset.col_a||"");setColB(editDataset.col_b||"");setDecimals(editDataset.decimals??2);const cats:string[]=Array.isArray(editDataset.taxonomy_categories)?editDataset.taxonomy_categories:[];const terms:string[]=Array.isArray(editDataset.taxonomy_terms)?editDataset.taxonomy_terms:[];const tx:Record<string,Set<string>>={};cats.forEach((c)=>{tx[c]=new Set<string>(terms.filter(t=> (taxoMap[c]||[]).includes(t))) });setTaxonomy(tx)} ,[open,editDataset, taxoMap]);
// once datasets loaded, finish hydrating A/B
useEffect(()=>{if(!open||!editDataset||datasets.length===0)return;const matchByTable=(tbl:string|undefined|null)=>datasets.find(d=>d.table===tbl)||null;setDatasetA(matchByTable(editDataset.table_a));if(!editDataset.use_scalar_b)setDatasetB(matchByTable(editDataset.table_b));},[open,editDataset,datasets]);
// auto-fill columns when dataset changes
useEffect(()=>{if(datasetA&&(!colA||colA.trim()===""))setColA(datasetA.defaultCol||"value")},[datasetA]);useEffect(()=>{if(datasetB&&!useScalarB&&(!colB||colB.trim()===""))setColB(datasetB.defaultCol||"value")},[datasetB,useScalarB]);
// helpers
const methodSymbol=useMemo(()=>({ratio:"÷",multiply:"×",sum:"+",difference:"−"}[method]),[method]);const computedFormula=useMemo(()=>{const rhs=useScalarB?String(scalarB):`B.${colB||"value"}`;return `A.${colA||"value"} ${methodSymbol} ${rhs}`},[useScalarB,scalarB,colA,colB,methodSymbol]);const formatNumber=(v:number|null)=>v==null||isNaN(v as any)?"":Number(v).toLocaleString(undefined,{maximumFractionDigits:decimals});
// preview
async function doPreview(){if(!datasetA||(!datasetB&&!useScalarB)){alert("Select Dataset A and (Dataset B or a scalar).");return}setLoadingPreview(true);const {data,error}=await supabase.rpc("simulate_join_preview_autoaggregate",{p_table_a:datasetA.table,p_table_b:useScalarB?null:datasetB?.table??null,p_col_a:colA||"value",p_col_b:useScalarB?null:colB||"value",p_country_iso:countryIso,p_method:method,p_target_level:targetLevel,p_use_scalar_b:useScalarB,p_scalar_b_val:useScalarB?scalarB:null,p_limit:200,p_normalize_percent:normalizePct});setLoadingPreview(false);if(error){alert("Preview error: "+error.message);return}setPreview(data||[])}
// save
async function doSave(){if(!datasetA||(!datasetB&&!useScalarB)){alert("Select Dataset A and (Dataset B or a scalar).");return}const catKeys=Object.keys(taxonomy);const termVals=catKeys.flatMap(c=>Array.from(taxonomy[c]||[]));const {error}=await supabase.rpc("create_derived_dataset_v2",{p_title:title||`Derived (${targetLevel})`,p_table_a:datasetA.table,p_table_b:useScalarB?null:datasetB?.table??null,p_col_a:colA||"value",p_col_b:useScalarB?null:colB||"value",p_admin_level:targetLevel,p_method:method,p_is_parametric:isParametric,p_scalar_b_val:useScalarB?scalarB:null,p_normalize_percent:normalizePct,p_debug:false});if(error){alert("Save failed: "+error.message);return}alert(editDataset?"✅ Changes saved.":"✅ Derived dataset created.");onClose()}
// taxonomy cell
function TaxoBlock(){const cats=Object.keys(taxoMap);if(cats.length===0)return null;return(<div className="space-y-2">{cats.map((cat)=>{const checked=!!taxonomy[cat];return(<div key={cat} className="border rounded p-2"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={checked} onChange={e=>{setTaxonomy(prev=>{const next={...prev};if(e.target.checked){if(!next[cat])next[cat]=new Set<string>();}else{delete next[cat]}return next})}}/>{cat}</label>{checked&&(<div className="mt-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 2xl:grid-cols-10 gap-x-3 gap-y-1 max-h-40 overflow-y-auto pr-1">{(taxoMap[cat]||[]).map(term=>(<label key={term} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={!!taxonomy[cat]?.has(term)} onChange={e=>{setTaxonomy(prev=>{const n={...prev};if(!n[cat])n[cat]=new Set<string>();if(e.target.checked)n[cat]!.add(term);else n[cat]!.delete(term);return n})}}/>{term}</label>))}</div>)}</div>)})}</div>)}
// grouped dataset options
const grouped=useMemo(()=>{const by:Record<Source,DatasetOption[]>= {core:[],gis:[],other:[],derived:[]};datasets.forEach(d=>by[d.source].push(d));groupOrder.forEach(g=>by[g].sort((a,b)=>a.title.localeCompare(b.title)));return by},[datasets]);
if(!open)return null;
return(<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-white rounded-2xl p-5 w-[96%] max-w-5xl max-h-[92vh] overflow-y-auto text-sm">
<div className="flex items-center gap-3 mb-3"><h2 className="text-lg font-semibold">{editDataset?"Edit Derived Dataset":"Create Derived Dataset"}</h2><span className="text-xs opacity-60">{loading?"loading…":""}</span></div>
<div className="flex flex-col gap-2 mb-3 md:flex-row">
<input className="border p-1 rounded flex-1" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/>
<input className="border p-1 rounded flex-1" placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)}/>
<select className="border p-1 rounded w-28" value={targetLevel} onChange={e=>setTargetLevel(e.target.value)}>{["ADM0","ADM1","ADM2","ADM3","ADM4"].map(l=><option key={l}>{l}</option>)}</select>
<select className="border p-1 rounded w-28" value={decimals} onChange={e=>setDecimals(parseInt(e.target.value))}>{[0,1,2,3].map(d=><option key={d} value={d}>{d} dec</option>)}</select>
</div>
<div className="flex gap-2 mb-2 items-center">
{(["ratio","multiply","sum","difference"] as Method[]).map(m=>(<button key={m} onClick={()=>setMethod(m)} className={`px-2 py-1 border rounded ${method===m?"text-white":""}`} style={{background:method===m?ACCENT:"transparent",borderColor:"#e5e7eb"}}>{m}</button>))}
<div className="ml-auto flex items-center gap-4">
<label className="text-xs flex items-center gap-1"><input type="checkbox" checked={isParametric} onChange={e=>setIsParametric(e.target.checked)}/>Parametric</label>
<label className="text-xs flex items-center gap-1"><input type="checkbox" checked={normalizePct} onChange={e=>setNormalizePct(e.target.checked)}/>Normalize %</label>
</div>
</div>
<div className="flex gap-2 mb-3">{[["A",datasetA,setDatasetA],["B",datasetB,setDatasetB]].map(([label,ds,setter],i)=>!useScalarB||label==="A"?(<select key={label as string} className="border p-1 rounded flex-1" value={(ds as any)?.id||""} onChange={e=>(setter as any)(datasets.find(d=>d.id===e.target.value)||null)} disabled={!!editDataset}><option value="">{`Select Dataset ${label}`}</option>{groupOrder.map(g=>(<optgroup key={g} label={g.toUpperCase()}>{grouped[g].map(d=> <option key={d.id} value={d.id}>{d.title}</option>)}</optgroup>))}</select>):null)}
<label className="text-xs flex items-center gap-1 ml-auto"><input type="checkbox" checked={useScalarB} onChange={e=>setUseScalarB(e.target.checked)}/>Use Scalar B</label>{useScalarB&&(<input type="number" className="border p-1 rounded w-28 text-right" value={scalarB} onChange={e=>setScalarB(parseFloat(e.target.value||"0"))}/>)}
</div>
<div className="flex gap-2 mb-3 items-center">
<input className="border p-1 rounded w-44" value={colA} onChange={e=>setColA(e.target.value)} placeholder="Column A"/>
{!useScalarB&&(<input className="border p-1 rounded w-44" value={colB} onChange={e=>setColB(e.target.value)} placeholder="Column B"/>)}
<button onClick={doPreview} className="ml-auto px-3 py-1 text-white rounded" style={{background:ACCENT}}>{loadingPreview?"Loading…":"Preview"}</button>
</div>
<p className="text-xs italic mb-2 break-all">Derived = {computedFormula}</p>
<div className="max-h-56 overflow-y-auto border rounded text-xs mb-4"><table className="w-full"><thead className="bg-gray-100 sticky top-0"><tr><th className="p-1 text-left">Pcode</th><th className="p-1 text-left">Name</th><th className="p-1 text-right">A</th><th className="p-1 text-right">B</th><th className="p-1 text-right">Derived</th><th className="p-1 text-left">Join</th><th className="p-1 text-left">Src A</th><th className="p-1 text-left">Src B</th></tr></thead><tbody>{preview.map((r:any,i:number)=>(<tr key={i} className="border-t"><td className="p-1">{r.join_key}</td><td className="p-1">{r.place_name??"—"}</td><td className="p-1 text-right">{formatNumber(r.a)}</td><td className="p-1 text-right">{formatNumber(r.b)}</td><td className="p-1 text-right font-medium">{formatNumber(r.derived)}</td><td className="p-1">{r.join_status}</td><td className="p-1">{r.source_level_a}</td><td className="p-1">{r.source_level_b}</td></tr>))}</tbody></table></div>
<h3 className="text-sm font-semibold mb-2">Assign Taxonomy</h3>
<TaxoBlock/>
<div className="flex justify-end gap-2 mt-4">
<button onClick={onClose} className="px-3 py-1 border rounded">Cancel</button>
<button onClick={doSave} className="px-3 py-1 text-white rounded" style={{background:ACCENT}}>{editDataset?"Save Changes":"Save Derived"}</button>
</div>
</div></div>)}
