"use client";

import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { supabaseBrowser as supabase } from "@/lib/supabase/supabaseBrowser";
import { MapContainer, TileLayer, GeoJSON } from "react-leaflet";
import "leaflet/dist/leaflet.css";

type Dataset = {
  id: string;
  title: string;
  result_table: string;
  admin_level: string;
  category: string;
  subcategory: string;
};

export default function DashboardPage({
  params,
}: {
  params: { id: string; instance_id: string };
}) {
  const [datasets, setDatasets] = useState<Dataset[]>([]);
  const [selected, setSelected] = useState<string>("");
  const [geoData, setGeoData] = useState<any>(null);

  useEffect(() => {
    loadDatasets();
  }, []);

  async function loadDatasets() {
    const { data, error } = await supabase
      .from("instance_layers")
      .select("id, result_table, category, subcategory")
      .eq("instance_id", params.instance_id);

    if (!data) return;
    // augment with readable titles
    const formatted = data.map((d) => ({
      id: d.id,
      title: `${d.category} – ${d.result_table}`,
      result_table: d.result_table,
      admin_level: d.subcategory || "ADM3",
      category: d.category,
      subcategory: d.subcategory,
    }));
    setDatasets(formatted);
  }

  async function loadMapData(result_table: string) {
    if (!result_table) return;
    const { data, error } = await supabase.rpc("get_geojson_for_result_table", {
      p_result_table: result_table,
    });
    if (error) console.error(error);
    setGeoData(data);
  }

  useEffect(() => {
    if (selected) loadMapData(selected);
  }, [selected]);

  return (
    <div className="flex flex-col h-[100vh] bg-white">
      {/* Header */}
      <header className="p-3 border-b flex justify-between items-center print:hidden">
        <h1 className="text-lg font-semibold text-[color:var(--gsc-green)]">
          SSC Dashboard
        </h1>
        <select
          className="border rounded px-2 py-1 text-sm"
          value={selected}
          onChange={(e) => setSelected(e.target.value)}
        >
          <option value="">Select dataset</option>
          {datasets.map((d) => (
            <option key={d.id} value={d.result_table}>
              {d.title}
            </option>
          ))}
        </select>
      </header>

      {/* Map area */}
      <main className="flex-1 relative">
        {geoData ? (
          <MapContainer
            center={[12.8797, 121.774]} // Philippines default center
            zoom={6}
            className="w-full h-full"
          >
            <TileLayer
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              attribution="© OpenStreetMap"
            />
            <GeoJSON
              data={geoData}
              style={(feature: any) => ({
                fillColor: getColor(feature.properties.score),
                color: "#444",
                weight: 0.5,
                fillOpacity: 0.75,
              })}
            />
          </MapContainer>
        ) : (
          <div className="p-10 text-gray-500 text-center">
            Select a dataset to view the map.
          </div>
        )}

        {/* Legend */}
        {geoData && (
          <div className="absolute bottom-5 right-5 bg-white p-3 rounded shadow text-xs print:shadow-none print:border">
            <h3 className="font-semibold mb-1 text-gray-700">Legend (Score)</h3>
            {[1, 2, 3, 4, 5].map((s) => (
              <div key={s} className="flex items-center gap-2">
                <span
                  className="inline-block w-4 h-4"
                  style={{ backgroundColor: getColor(s) }}
                />
                <span>{s}</span>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="p-2 text-[10px] text-gray-500 text-center border-t print:hidden">
        Generated by SSC Toolset — {new Date().toLocaleDateString()}
      </footer>
    </div>
  );
}

// Simple color ramp for 1–5 scale
function getColor(v: number) {
  return v === 1
    ? "#006837"
    : v === 2
    ? "#31a354"
    : v === 3
    ? "#78c679"
    : v === 4
    ? "#c2e699"
    : "#ffffcc";
}
